# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 28, 5, 16, 5, 713372, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
