# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0002_auto_20160528_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('NZ', 'NZ'), ('INTERNATIONAL', 'International'), ('TECH', 'Tech'), ('SPORT', 'Sport')], default='NZ', max_length=15),
        ),
    ]
