# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0003_auto_20160528_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=140),
        ),
    ]
