# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0004_auto_20160528_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
